print('Hola + Gabo')
print('Hola \"Gabo\"')
print('Esta es una linea\nY esta es otra linea\nY porqué vergans no... Otra linea :v')
print('\tTabular es de mamados, tu no metes cara saramanbiche, >:v.i.')
print('Topa esto, rey... This isn\'t a number... Pa\' su mecha... :v, A que no te lo esperabas...')
print('Así se escribe una barra invertida, rey \\, ¿Vas a estar así')
print('Linea 1\nLinea 2\nLinea 3')
print('A\tB\tC\nD\tE\tF\nG\tH\tI')
print('Barra Normnal: /\nBarra Invertida: \\')